### ISSUE TITLE
Output is printed twice to console

### ISSUE THREAD

**Issue by pinkj24** [abdokhaire/sfdx-build#6]
When the plugin is ran as a terminal command and the output is redirected to a file using `>` the resulting file contains the Package.xml twice and is therefore invalid XML.
This can be seen by the duplication of the following lines (and everything between them) in the output:
```
<?xml version="1.0" encoding="utf-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">

</Package>
```

**Comment by ahmed-khaire** [comment]
Thanks, @pinkj24  for the fix
